export type SystemConcept = {
  id: string
  name: string
  plain: string
  definition: string
  lesson: string
  group: string
  dependencies: string[]
  output: string
  confused: string
}

const concept = (
  id: string,
  name: string,
  plain: string,
  definition: string,
  lesson: string,
  group: string,
  dependencies: string[],
  output: string,
  confused: string,
): SystemConcept => ({ id, name, plain, definition, lesson, group, dependencies, output, confused })

export const concepts: SystemConcept[] = [
  concept(
    'react',
    'ReAct',
    '判断、行动和观察交替进行。',
    'Reason / Act / Observe 的经典 Agent 思想之一，现代系统还常包含计划、状态、验证、重试与约束。',
    'agent-loop',
    'Runtime',
    ['reasoning', 'observation'],
    '后续行动',
    'ReAct 不等于现代 Agent 的全部。',
  ),
  concept(
    'workflow',
    'Workflow',
    '按预先定义的路径处理任务。',
    '由程序预先定义执行路径的流程，可包含条件分支、异常处理、循环和模型节点。',
    'workflow-vs-agent',
    'Runtime',
    [],
    '可预测的执行流程',
    '工作流能处理预先写好的异常，不等于只能直线执行。',
  ),
  concept(
    'multi-agent',
    'Multi-Agent',
    '把复杂任务交给职责不同的 Agent。',
    '多个 Agent 通过明确任务、上下文边界与协调机制协作完成任务的系统。',
    'multi-agent',
    'Runtime',
    ['agent', 'handoff'],
    '协作结果',
    'Agent 数量增加不保证质量提高。',
  ),
  concept(
    'agent-as-tool',
    'Agent-as-Tool',
    '把子 Agent 当作一项可调用能力。',
    '管理 Agent 委派子任务并接收结果，外层任务控制权仍由管理者保持。',
    'multi-agent',
    'Runtime',
    ['multi-agent'],
    '返回管理者的子任务结果',
    '不等于 Handoff 转移后续控制权。',
  ),
  concept(
    'mcp-client',
    'MCP Client',
    '运行系统内负责对接的一端。',
    '宿主应用中维护与 MCP Server 连接并交换协议消息的组件。',
    'mcp',
    'Tools',
    ['harness'],
    '协议请求',
    '不是外部服务本身，也不是模型。',
  ),
  concept(
    'mcp-server',
    'MCP Server',
    '把外部能力按协议提供出来。',
    '通过 MCP 协议暴露 Tool、Resource 或 Prompt 等能力的服务。',
    'mcp',
    'Tools',
    ['mcp-client'],
    '能力描述、工具结果或资源内容',
    '不是每个 Server 都必须支持全部能力。',
  ),
  concept(
    'resource',
    'Resource',
    '让系统读取可用的资料内容。',
    'MCP Server 暴露的可供客户端读取的信息资源；读取结果是否进入 Context 由宿主组织。',
    'mcp',
    'Tools',
    ['mcp-server'],
    '资源内容',
    'Resource、Tool 和 Prompt 的用途不同。',
  ),
  concept(
    'mcp-prompt',
    'MCP Prompt',
    '服务提供可复用的提示模板。',
    'MCP Server 可提供供客户端选用的提示模板，帮助组织交互内容。',
    'mcp',
    'Tools',
    ['mcp-server'],
    '提示模板',
    '不是模型自动获得的最高优先级指令。',
  ),
  concept(
    'transport',
    'Transport',
    '协议消息通过什么通道往返。',
    '承载 MCP 消息传输的通信方式，例如本地 stdio 或远程 Streamable HTTP。',
    'mcp',
    'Tools',
    ['mcp-client', 'mcp-server'],
    '通信通道',
    '传输方式本身不负责模型推理或全部权限控制。',
  ),
  concept(
    'context-window',
    'Context Window',
    '这一次能处理的信息有上限。',
    '模型单次推理可以处理的信息范围；具体输入输出预算由模型和服务限制决定。',
    'context',
    'Context',
    ['context'],
    '单次上下文预算',
    '不是 Memory 仓库的容量。',
  ),
  concept(
    'checkpoint',
    'Checkpoint',
    '保存能从中继续工作的进度点。',
    '将任务目标、当前状态、决定、待办和必要证据等保存为可恢复的检查点。',
    'compaction',
    'Runtime',
    ['state'],
    '恢复任务所需的状态',
    '压缩摘要可能丢失细节，关键证据需保留可追溯引用。',
  ),
  concept(
    'retrieved-context',
    'Retrieved Context',
    '刚找到并选入本次任务的资料。',
    '外部检索后被选择加入模型 Context 的相关内容。',
    'rag',
    'Context',
    ['retrieval', 'rerank'],
    '模型可见的检索片段',
    '不是模型参数中的知识，也不是整个知识库。',
  ),
  concept(
    'user',
    'User',
    '把要完成的事告诉系统。',
    '提出任务目标、约束和验收要求的使用者。',
    'system-overview',
    '入口',
    [],
    '任务与约束',
    '用户愿望不等于系统拥有执行权限。',
  ),
  concept(
    'router',
    'Input / Router',
    '把任务交给适合的入口。',
    '根据输入和系统策略选择后续处理路径的路由组件。',
    'harness',
    '入口',
    ['user'],
    '任务路由',
    '路由可用规则或模型实现，并非只能由模型决定。',
  ),
  concept(
    'context-engineering',
    'Context Engineering',
    '整理这一次真正需要的信息。',
    '为当前任务选择、组织、补充和控制模型 Context 的过程。',
    'context',
    'Context',
    ['prompt', 'history', 'memory', 'rag', 'schema'],
    'Context',
    'Prompt 只是其中一部分。',
  ),
  concept(
    'prompt',
    'Prompt',
    '你给模型的要求和指令。',
    '给模型的输入或指令，是 Context 的组成部分之一。',
    'context',
    'Context',
    ['user'],
    '输入指令',
    '不等于全部 Context。',
  ),
  concept(
    'history',
    'History',
    '本次对话中仍有用的记录。',
    '被选入本次推理上下文的历史消息和工具结果。',
    'context',
    'Context',
    [],
    '对话信息',
    '并非所有历史都永远可见。',
  ),
  concept(
    'memory',
    'Memory',
    '跨任务存下重要经验，需要时再取。',
    '可跨轮次或任务保存和检索的信息或状态。保存的信息不自动全部进入当前 Context。',
    'memory',
    'Context',
    [],
    '取出的相关历史信息',
    'Memory 是存储；Context 是本次可见信息；RAG 是检索增强方法。',
  ),
  concept(
    'rag',
    'RAG',
    '临时查资料，只把相关片段交给模型。',
    'Retrieval-Augmented Generation：从外部知识源检索与当前任务相关的信息，并将相关结果加入 Context 的方法。',
    'rag',
    'Context',
    ['retrieval', 'embedding', 'vector-db', 'rerank'],
    'Retrieved Context',
    'Memory、Web Search、Fine-tuning。RAG 不更新模型参数，也不必使用向量检索。',
  ),
  concept(
    'schema',
    'Tool Schema',
    '工具的名称、用途和参数说明。',
    '描述 Tool 名称、用途和参数结构的说明，供模型生成符合约定的调用请求。',
    'tools',
    'Tools',
    [],
    '可用工具说明',
    '不是本次 Tool Call，也不代表已经执行。',
  ),
  concept(
    'context',
    'Context',
    '模型这一次能看到的工作台。',
    '模型当前这一次推理真正可见的信息集合。',
    'context',
    'Context',
    ['context-engineering'],
    '模型本次输入',
    'Context Window 限制单次处理范围，不是长期记忆容量。',
  ),
  concept(
    'model',
    'Model',
    '根据眼前信息生成回答或下一步请求。',
    '用训练得到的参数处理 Context 并逐步生成输出的计算模型。',
    'model-inside',
    'Model',
    ['context'],
    '回答、行动请求或交接请求',
    '模型不直接访问互联网；外部动作由运行系统执行。',
  ),
  concept(
    'reasoning',
    'Reasoning',
    '分析线索，判断下一步。',
    '模型围绕任务执行多步推导、比较与判断的能力或过程；本图展示教学摘要。',
    'agent-loop',
    'Model',
    ['model'],
    '行动依据',
    '本图不显示真实模型隐藏推理内容。',
  ),
  concept(
    'planning',
    'Planning',
    '把目标拆成可调整的步骤。',
    '制定并根据观察更新后续行动计划的过程。',
    'agent-loop',
    'Model',
    ['model'],
    '计划',
    '计划不是一次性不变的执行保证。',
  ),
  concept(
    'call',
    'Tool Call',
    '填写本次要做什么的请求单。',
    '模型针对某次任务生成的具体结构化工具调用请求。',
    'tools',
    'Tools',
    ['model', 'schema'],
    '待执行请求',
    '生成请求不意味着工具已经执行。',
  ),
  concept(
    'harness',
    'Harness',
    '让模型能够持续工作的运行系统。',
    '承载 Context 管理、Agent Loop、Tool 执行、状态、权限、重试、Guardrail、Trace 等能力的运行系统。',
    'harness',
    'Runtime',
    ['call'],
    '经过检查、调度的执行',
    'Harness 和 Model 职责不同，具体系统的模块边界会变化。',
  ),
  concept(
    'mcp',
    'MCP',
    '用统一协议连接外部能力。',
    'Model Context Protocol：连接外部 Tool、Resource 和 Prompt 等能力的标准协议与基础设施层。',
    'mcp',
    'Tools',
    ['harness'],
    '协议请求与响应',
    'MCP 不是模型、Agent 或工具本身；它不是所有工具调用的必经之路。',
  ),
  concept(
    'tools',
    'Tools',
    '真正读取、搜索和处理外部内容。',
    '系统向模型暴露的、可以被请求调用的外部能力，由运行系统调度执行。',
    'tools',
    'Tools',
    ['harness'],
    'Tool Result',
    'File Tool 读指定文件；RAG 从资料库找相关片段。',
  ),
  concept(
    'guardrail',
    'Guardrails',
    '先检查边界，再放行动作。',
    '对输入、动作、工具调用或输出进行限制和检查的控制机制。',
    'guardrail',
    'Runtime',
    ['harness'],
    '允许、拒绝或请求人工干预',
    '不代表每个低风险动作都必须人工批准。',
  ),
  concept(
    'approval',
    'Human Approval',
    '由人决定关键动作是否继续。',
    '在关键或高风险节点引入人工判断、批准或干预。',
    'guardrail',
    'Runtime',
    ['guardrail'],
    '批准或拒绝',
    '无人回答不等于批准；批准也不能保证执行成功。',
  ),
  concept(
    'external',
    'External World',
    '文件、网站、数据库等外部环境。',
    '工具可在授权范围内访问或修改的外部系统与资源。',
    'tools',
    'Tools',
    ['tools', 'mcp'],
    '执行结果',
    '外部资料也可能不可靠或含有恶意指令。',
  ),
  concept(
    'observation',
    'Observation',
    '看一看刚才实际发生了什么。',
    '系统接收到的工具结果或环境反馈，经组织加入 Context 后供模型继续判断。',
    'agent-loop',
    'Runtime',
    ['external'],
    '更新的 Context',
    'Observation 不是模型猜测的执行结果。',
  ),
  concept(
    'verifier',
    'Verification',
    '用可检查条件核对有没有完成。',
    '使用可检查条件判断任务是否真正完成，例如测试、来源核验和要求逐项检查。',
    'verification',
    'Runtime',
    ['model'],
    'PASS 或 FAIL 的证据',
    '模型主观 Self-check 无法替代真实外部验证。',
  ),
  concept(
    'loop',
    'Agent Loop',
    '结果不够，就带着新信息继续。',
    'Agent 持续执行 Observe → Reason / Plan → Act → Observe → Verify 的运行循环。',
    'agent-loop',
    'Runtime',
    ['observation', 'verifier'],
    '下一轮决策或停止',
    'ReAct 是经典思想之一，不等于现代 Agent 的全部。',
  ),
  concept(
    'final',
    'Final',
    '满足要求后，把结果交给用户。',
    '依据当前任务的完成条件，结束本轮任务并输出最终结果。',
    'verification',
    'Runtime',
    ['verifier'],
    '经过核验的交付',
    '流畅的最终文字不能替代验证证据。',
  ),
  concept(
    'state',
    'State / Trace',
    '记录进度与过程，方便恢复和追查。',
    'State 保存当前执行状态；Trace 记录系统执行轨迹。它们可持久化，但用途不同。',
    'harness',
    'Runtime',
    ['final'],
    '状态与过程记录',
    'Trace 不一定全部进入 Context，也不自动成为长期 Memory。',
  ),
  concept(
    'compaction',
    'Compaction',
    '压缩旧记录，带着关键线索继续。',
    '在长任务中压缩历史 Context，并保留继续工作所需的关键状态。',
    'compaction',
    'Runtime',
    ['context', 'state'],
    '紧凑上下文和检查点',
    '不是删除 Memory，也不是无限扩大 Context Window。',
  ),
  concept(
    'agent',
    'Agent',
    '根据反馈决定下一步的完整系统。',
    '由模型根据当前状态动态决定下一步行动的系统，通常结合 Context、Tools、Loop、State 与 Runtime。',
    'workflow-vs-agent',
    'Runtime',
    ['model', 'context', 'harness'],
    '连续完成任务',
    '不是模型本身，也不是越多 Agent 越好。',
  ),
  concept(
    'handoff',
    'Handoff',
    '把接下来由谁负责这件事交出去。',
    '将当前任务的控制权转移给另一个 Agent；后续是否返回取决于系统设计。',
    'multi-agent',
    'Runtime',
    ['agent'],
    '新的任务负责人',
    'Agent-as-Tool 是子任务结果返回管理者，两者控制流不同。',
  ),
  concept(
    'eval',
    'Eval',
    '用一组任务，比较系统整体表现。',
    '用定义好的数据集、评价条件和指标评估系统能力或质量的过程。',
    'verification',
    'Runtime',
    ['verifier'],
    '评估结果',
    '单次任务 Verification 与批量 Eval 不完全等同。',
  ),
  concept(
    'token',
    'Token',
    '模型处理文字时使用的片段。',
    '由 tokenizer 划分的基本输入或输出单元，不固定等于一个汉字或一个单词。',
    'model-inside',
    'Model',
    [],
    'Token 序列',
    'Token 数量不等于字数。',
  ),
  concept(
    'embedding',
    'Embedding',
    '把内容变成可计算的数字表示。',
    '将内容映射到向量空间的表示方法，可用于模型内部计算，也常用于语义检索。',
    'model-inside',
    'Model',
    ['token'],
    '向量表示',
    '向量相近不保证事实正确；检索编码器和生成模型可以不同。',
  ),
  concept(
    'transformer',
    'Transformer',
    '通过多层计算处理上下文关系。',
    '以 Attention 等机制组成的神经网络架构，用于更新输入表示并生成输出。',
    'model-inside',
    'Model',
    ['embedding', 'attention'],
    '经过上下文处理的表示',
    '并不是每一层都对应一个独立业务功能。',
  ),
  concept(
    'attention',
    'Attention',
    '计算内容之间应怎样相互参考。',
    'Transformer 中根据输入表示计算上下文关系并聚合信息的机制。',
    'model-inside',
    'Model',
    ['embedding'],
    '结合关系的信息表示',
    '不是人的注意力，也不是可靠的因果解释。',
  ),
  concept(
    'function-calling',
    'Function Calling',
    '让模型按约定生成工具请求。',
    '模型生成结构化 Tool Call 的机制；具体执行交给 Harness 和 Tool Runtime。',
    'tools',
    'Tools',
    ['schema', 'model'],
    'Tool Call',
    'Function Calling 不等于 Tool Runtime。',
  ),
  concept(
    'retrieval',
    'Retrieval',
    '先从资料中找出候选内容。',
    '依据查询从外部信息源召回候选资料的过程。',
    'rag',
    'Context',
    [],
    '候选片段',
    '召回很多不代表最后放入 Context 的内容很多。',
  ),
  concept(
    'vector-db',
    'Vector Database',
    '存储并搜索数字表示的索引。',
    '支持向量存储、索引与相似度检索的数据系统。',
    'rag',
    'Context',
    ['embedding'],
    '相似内容候选',
    '不是所有 RAG 都必须使用向量数据库。',
  ),
  concept(
    'rerank',
    'Rerank',
    '把候选资料按当前问题重新排队。',
    '对已召回候选内容进行更细致的相关性排序，选择最终上下文。',
    'rag',
    'Context',
    ['retrieval'],
    '高相关片段',
    '排序不能保证资料可信，还需要核验来源。',
  ),
]

export const systemRows = [
  ['user', 'router'],
  ['prompt', 'history', 'memory', 'rag', 'schema'],
  ['context-engineering', 'context', 'compaction'],
  ['reasoning', 'model', 'planning', 'call', 'handoff'],
  ['loop', 'harness', 'mcp', 'tools', 'guardrail'],
  ['external', 'observation', 'approval'],
  ['verifier', 'final', 'state', 'eval'],
]
export const edges: [string, string][] = [
  ['user', 'router'],
  ['router', 'context-engineering'],
  ['prompt', 'context-engineering'],
  ['history', 'context-engineering'],
  ['memory', 'context-engineering'],
  ['rag', 'context-engineering'],
  ['schema', 'context-engineering'],
  ['context-engineering', 'context'],
  ['context', 'model'],
  ['context', 'compaction'],
  ['compaction', 'context'],
  ['model', 'reasoning'],
  ['model', 'planning'],
  ['model', 'call'],
  ['model', 'handoff'],
  ['call', 'harness'],
  ['harness', 'loop'],
  ['harness', 'mcp'],
  ['harness', 'tools'],
  ['harness', 'guardrail'],
  ['guardrail', 'approval'],
  ['approval', 'tools'],
  ['mcp', 'external'],
  ['tools', 'external'],
  ['external', 'observation'],
  ['observation', 'context'],
  ['model', 'verifier'],
  ['verifier', 'loop'],
  ['loop', 'context'],
  ['verifier', 'final'],
  ['final', 'state'],
  ['state', 'memory'],
  ['state', 'eval'],
]

export const taskTrace = [
  {
    node: 'user',
    label: '收到目标',
    detail: '研究最新 AI GPU，读取内部 PDF，生成有来源的比较报告，并检查结果。',
  },
  {
    node: 'memory',
    label: '取回偏好',
    detail: '取出“优先中文、列明来源”的历史偏好；只把相关项交给本次任务。',
  },
  {
    node: 'rag',
    label: '检索内部资料',
    detail: '指定 PDF 可用 File Tool 读取；当资料库有很多文件时，用 RAG 筛出相关片段。',
  },
  {
    node: 'context',
    label: '组织 Context',
    detail: '目标、规则、相关 PDF 片段、历史偏好和 Tool Schema 进入模型当前可见的信息。',
  },
  {
    node: 'call',
    label: '请求官方资料',
    detail: 'Model 生成搜索或浏览 Tool Call。这时还没有真正访问互联网。',
  },
  {
    node: 'harness',
    label: '运行系统执行',
    detail:
      'Harness 检查权限、路由工具并处理重试。若采用 MCP，Client 通过协议访问 Server 暴露的能力。',
  },
  {
    node: 'observation',
    label: '第一次结果不足',
    detail: '教学结果只有论坛转载，尚无官方证据。结果加入 Context 后，模型重新判断。',
  },
  {
    node: 'loop',
    label: '失败后继续',
    detail: 'Agent Loop 再次请求打开官方资料。ReAct 的行动与观察思想在此可见。',
  },
  {
    node: 'compaction',
    label: '保存继续工作的线索',
    detail:
      '长任务使 Context 接近容量。压缩重复日志，保留目标、证据、失败记录和待办。Memory 仍存在。',
  },
  {
    node: 'verifier',
    label: '核验报告',
    detail: '检查每条结论的来源、PDF 引用和用户要求。缺一项就回到循环修复，通过后才交付。',
  },
  {
    node: 'approval',
    label: '确认高风险动作',
    detail: '如果任务额外要求删除报告数据库，Guardrail 会暂停并请求人工决定。等待不是批准。',
  },
  {
    node: 'final',
    label: '完成并留存状态',
    detail:
      '交付通过检查的报告，保存状态、轨迹和经选择的记忆。Modern AI System = Model + Context Engineering + Harness。',
  },
]
