import { concepts } from '../final-system-map/concepts'
import type {
  ExploreCategory,
  ExploreConnection,
  ExploreDepth,
  ExploreNode,
  ExploreTaskStep,
  ExploreTourStop,
  NodeKind,
  Point3,
} from './types'

export const categoryLabels: Record<ExploreCategory, string> = {
  input: '任务入口',
  context: '本次工作台',
  model: '模型核心',
  harness: '运行与执行',
  external: '外部世界',
  verification: '检查与交付',
}

type NodePlacement = {
  id: string
  chineseLabel: string
  category: ExploreCategory
  level: ExploreDepth
  position: Point3
  kind: NodeKind
  parentId?: string
  responsibility: string
  related?: string[]
}

// These islands encode ownership, not an execution order. Connections encode flow.
const placements: NodePlacement[] = [
  {
    id: 'user',
    chineseLabel: '用户',
    category: 'input',
    level: 0,
    position: [-10, 3, -5],
    kind: 'input',
    responsibility: '提出目标、限制与验收要求。',
  },
  {
    id: 'context',
    chineseLabel: '本次上下文',
    category: 'context',
    level: 0,
    position: [-5, 2, -3],
    kind: 'context',
    responsibility: '向模型提供这一次真正可见的任务资料。',
    related: ['memory', 'rag', 'context-window'],
  },
  {
    id: 'model',
    chineseLabel: '模型',
    category: 'model',
    level: 0,
    position: [0, 1, 0],
    kind: 'model',
    responsibility: '根据 Context 生成回答或下一步请求；不自行执行外部操作。',
    related: ['harness', 'agent'],
  },
  {
    id: 'harness',
    chineseLabel: '运行系统',
    category: 'harness',
    level: 0,
    position: [5, 0, 0],
    kind: 'harness',
    responsibility: '组织上下文、检查权限、调度工具，并维护循环与运行记录。',
    related: ['model', 'agent', 'workflow'],
  },
  {
    id: 'external',
    chineseLabel: '外部世界',
    category: 'external',
    level: 0,
    position: [10, 0, -5],
    kind: 'external',
    responsibility: '提供可被授权访问的网页、文件、代码环境和服务。',
  },
  {
    id: 'final',
    chineseLabel: '最终交付',
    category: 'verification',
    level: 0,
    position: [-1, -1, 6],
    kind: 'final',
    responsibility: '在完成条件满足后，把结果与必要证据交还给用户。',
  },

  {
    id: 'memory',
    chineseLabel: '长期记忆',
    category: 'context',
    level: 1,
    position: [-8, 0.7, -1.4],
    kind: 'memory',
    parentId: 'context',
    responsibility: '保存跨任务信息，并按需取回相关项；不会自动全部塞入 Context。',
    related: ['rag', 'history', 'context'],
  },
  {
    id: 'rag',
    chineseLabel: '检索增强',
    category: 'context',
    level: 1,
    position: [-4.4, 4, -6.4],
    kind: 'rag',
    parentId: 'context',
    responsibility: '从资料库筛选相关内容，给当前回答补充可追溯的依据。',
    related: ['memory', 'files', 'context'],
  },
  {
    id: 'tools',
    chineseLabel: '可调用工具',
    category: 'harness',
    level: 1,
    position: [8, 0.7, -1.4],
    kind: 'tool',
    parentId: 'harness',
    responsibility: '按运行系统的调度，实际执行读取、检索或计算并返回结果。',
    related: ['schema', 'call', 'mcp'],
  },
  {
    id: 'loop',
    chineseLabel: '持续工作循环',
    category: 'harness',
    level: 1,
    position: [1.8, -1.4, 3.9],
    kind: 'loop',
    parentId: 'harness',
    responsibility: '将观察与检查结果带入下一轮，直到满足停止条件。',
    related: ['react', 'workflow', 'agent'],
  },
  {
    id: 'verifier',
    chineseLabel: '结果核验',
    category: 'verification',
    level: 1,
    position: [4, 0, 6],
    kind: 'check',
    parentId: 'harness',
    responsibility: '按来源、测试和任务要求等可检查条件给出 PASS 或 FAIL。',
    related: ['eval', 'guardrail'],
  },
  {
    id: 'guardrail',
    chineseLabel: '边界检查',
    category: 'harness',
    level: 1,
    position: [6.9, 2.7, 2.3],
    kind: 'gate',
    parentId: 'harness',
    responsibility: '检查动作是否允许；需要时拒绝、限制或暂停等待人工决定。',
    related: ['approval', 'verifier'],
  },

  {
    id: 'router',
    chineseLabel: '输入与路由',
    category: 'input',
    level: 2,
    position: [-10.8, 1, -7.2],
    kind: 'satellite',
    parentId: 'user',
    responsibility: '根据输入和策略，把请求交给合适的处理路径。',
  },
  {
    id: 'prompt',
    chineseLabel: '本次要求',
    category: 'context',
    level: 2,
    position: [-7.5, 3.8, -4.7],
    kind: 'satellite',
    parentId: 'context',
    responsibility: '表达任务要求与指令，是 Context 中的一部分。',
    related: ['context', 'context-engineering'],
  },
  {
    id: 'history',
    chineseLabel: '对话记录',
    category: 'context',
    level: 2,
    position: [-6.5, 4.8, -1.4],
    kind: 'satellite',
    parentId: 'context',
    responsibility: '提供被保留的历史消息与工具结果。',
    related: ['memory', 'compaction'],
  },
  {
    id: 'schema',
    chineseLabel: '工具说明',
    category: 'context',
    level: 2,
    position: [-2.9, 3.5, -2.1],
    kind: 'satellite',
    parentId: 'context',
    responsibility: '告诉模型可用工具的用途与参数格式。',
    related: ['call', 'tools', 'function-calling'],
  },
  {
    id: 'context-engineering',
    chineseLabel: '组织本次信息',
    category: 'context',
    level: 2,
    position: [-5.7, 0.1, -4.8],
    kind: 'satellite',
    parentId: 'context',
    responsibility: '选择、组织与控制真正放进模型本次输入的信息。',
    related: ['prompt', 'compaction'],
  },
  {
    id: 'context-window',
    chineseLabel: '上下文容量',
    category: 'context',
    level: 2,
    position: [-8.3, 3.7, 0.1],
    kind: 'satellite',
    parentId: 'context',
    responsibility: '限定单次推理可处理的信息范围。',
    related: ['memory', 'compaction'],
  },
  {
    id: 'retrieval',
    chineseLabel: '召回候选',
    category: 'context',
    level: 2,
    position: [-5.8, 5.5, -8.1],
    kind: 'satellite',
    parentId: 'rag',
    responsibility: '从信息源中找出与查询相关的候选资料。',
  },
  {
    id: 'vector-db',
    chineseLabel: '向量索引',
    category: 'context',
    level: 2,
    position: [-7.3, 3.2, -7.5],
    kind: 'satellite',
    parentId: 'rag',
    responsibility: '存储与索引向量，并支持相似度检索；RAG 也能用其他检索方式。',
    related: ['embedding', 'retrieval'],
  },
  {
    id: 'rerank',
    chineseLabel: '候选重排',
    category: 'context',
    level: 2,
    position: [-2.7, 5.6, -7.9],
    kind: 'satellite',
    parentId: 'rag',
    responsibility: '重新比较候选资料，挑出更适合本次问题的片段。',
  },
  {
    id: 'retrieved-context',
    chineseLabel: '选中的资料',
    category: 'context',
    level: 2,
    position: [-2.5, 2.1, -5.7],
    kind: 'satellite',
    parentId: 'rag',
    responsibility: '承载经检索筛选后，实际加入本次 Context 的内容。',
    related: ['observation', 'memory'],
  },

  {
    id: 'reasoning',
    chineseLabel: '分析与判断',
    category: 'model',
    level: 2,
    position: [-1.4, 3.8, 0.9],
    kind: 'satellite',
    parentId: 'model',
    responsibility: '围绕现有信息比较与判断下一步；这里仅用教学摘要说明。',
    related: ['planning', 'react'],
  },
  {
    id: 'planning',
    chineseLabel: '安排步骤',
    category: 'model',
    level: 2,
    position: [1.6, 3.5, -0.7],
    kind: 'satellite',
    parentId: 'model',
    responsibility: '拆解目标，并随反馈调整后续步骤。',
    related: ['reasoning', 'workflow'],
  },
  {
    id: 'call',
    chineseLabel: '工具请求单',
    category: 'model',
    level: 2,
    position: [2.7, 1.2, -1.2],
    kind: 'satellite',
    parentId: 'model',
    responsibility: '表达具体要调用的工具及参数，等待运行系统执行。',
    related: ['schema', 'function-calling', 'tools'],
  },
  {
    id: 'function-calling',
    chineseLabel: '生成结构化请求',
    category: 'model',
    level: 2,
    position: [0.5, 3.8, -3.5],
    kind: 'satellite',
    parentId: 'model',
    responsibility: '让模型按工具约定生成结构化调用请求。',
    related: ['call', 'schema', 'tools'],
  },
  {
    id: 'token',
    chineseLabel: '信息片段',
    category: 'model',
    level: 2,
    position: [-1.7, -0.9, -2.4],
    kind: 'satellite',
    parentId: 'model',
    responsibility: '作为模型输入、输出与预算计算的基本片段。',
  },
  {
    id: 'embedding',
    chineseLabel: '数字表示',
    category: 'model',
    level: 2,
    position: [-0.2, -1.3, -4.3],
    kind: 'satellite',
    parentId: 'model',
    responsibility: '把内容编码为数字向量，支持模型计算或语义检索。',
    related: ['vector-db', 'rag'],
  },
  {
    id: 'attention',
    chineseLabel: '上下文关联计算',
    category: 'model',
    level: 2,
    position: [1.3, 0.2, -3.9],
    kind: 'satellite',
    parentId: 'model',
    responsibility: '计算输入表示之间如何相互参考与汇聚信息。',
  },
  {
    id: 'transformer',
    chineseLabel: '多层模型结构',
    category: 'model',
    level: 2,
    position: [-2, 1.5, 2.5],
    kind: 'satellite',
    parentId: 'model',
    responsibility: '通过 Attention 等多层结构更新输入表示并生成输出。',
    related: ['attention', 'embedding'],
  },

  {
    id: 'mcp',
    chineseLabel: '连接能力的协议',
    category: 'harness',
    level: 2,
    position: [7.2, 0.4, -4.1],
    kind: 'satellite',
    parentId: 'harness',
    responsibility: '用标准协议连接 Tool、Resource 和 Prompt 等能力；不是所有工具的必经路径。',
    related: ['tools', 'mcp-client', 'mcp-server'],
  },
  {
    id: 'mcp-client',
    chineseLabel: '宿主连接端',
    category: 'harness',
    level: 2,
    position: [5.6, 2.3, -4],
    kind: 'satellite',
    parentId: 'mcp',
    responsibility: '在宿主运行系统内建立连接并交换 MCP 消息。',
    related: ['mcp-server', 'transport'],
  },
  {
    id: 'state',
    chineseLabel: '当前执行状态',
    category: 'harness',
    level: 2,
    position: [4.2, 2.4, 2.5],
    kind: 'satellite',
    parentId: 'harness',
    responsibility: '保存当前步骤、结果与待办，供后续决策和恢复使用。',
    related: ['trace', 'checkpoint', 'memory'],
  },
  {
    id: 'retry',
    chineseLabel: '受控重试',
    category: 'harness',
    level: 2,
    position: [4.3, -1.8, -2.3],
    kind: 'satellite',
    parentId: 'harness',
    responsibility: '在可重试错误后按次数、等待与幂等策略再次尝试。',
    related: ['loop', 'guardrail'],
  },
  {
    id: 'trace',
    chineseLabel: '执行轨迹',
    category: 'harness',
    level: 2,
    position: [7.2, -1.4, 1.5],
    kind: 'satellite',
    parentId: 'harness',
    responsibility: '记录调用、结果、时序与检查事件，方便定位问题和复盘。',
    related: ['state', 'memory', 'eval'],
  },
  {
    id: 'workflow',
    chineseLabel: '预设流程',
    category: 'harness',
    level: 2,
    position: [3.6, 4.9, 0.5],
    kind: 'satellite',
    parentId: 'harness',
    responsibility: '用程序定义固定路径、分支与异常处理。',
    related: ['agent', 'loop', 'planning'],
  },
  {
    id: 'agent',
    chineseLabel: '动态行动系统',
    category: 'harness',
    level: 2,
    position: [5.9, 4.9, -1.7],
    kind: 'satellite',
    parentId: 'harness',
    responsibility: '让模型结合状态与反馈动态决定下一步，由运行系统落实行动。',
    related: ['model', 'harness', 'workflow', 'multi-agent'],
  },
  {
    id: 'react',
    chineseLabel: '判断、行动、观察',
    category: 'harness',
    level: 2,
    position: [0.1, -2, 3.6],
    kind: 'satellite',
    parentId: 'loop',
    responsibility: '用判断、行动与观察交替的思想组织后续行动。',
    related: ['loop', 'reasoning', 'observation'],
  },
  {
    id: 'multi-agent',
    chineseLabel: '多个 Agent 协作',
    category: 'harness',
    level: 2,
    position: [8.5, 4.8, 0.1],
    kind: 'satellite',
    parentId: 'harness',
    responsibility: '按清楚的职责与上下文边界组织多个 Agent 协作。',
    related: ['agent', 'handoff', 'agent-as-tool'],
  },
  {
    id: 'handoff',
    chineseLabel: '交接负责人',
    category: 'harness',
    level: 2,
    position: [10.5, 4, 1.6],
    kind: 'satellite',
    parentId: 'multi-agent',
    responsibility: '把接下来的任务控制权转交给另一个 Agent。',
    related: ['agent-as-tool'],
  },
  {
    id: 'agent-as-tool',
    chineseLabel: '委派子任务',
    category: 'harness',
    level: 2,
    position: [8.8, 6.7, 2.1],
    kind: 'satellite',
    parentId: 'multi-agent',
    responsibility: '调用子 Agent 并接收结果，管理者保留外层控制权。',
    related: ['handoff'],
  },
  {
    id: 'compaction',
    chineseLabel: '压缩工作记录',
    category: 'harness',
    level: 2,
    position: [-5.1, -1.9, 0.7],
    kind: 'satellite',
    parentId: 'context',
    responsibility: '压缩历史 Context，保留目标、证据引用、进度和待办。',
    related: ['memory', 'context-window', 'checkpoint'],
  },
  {
    id: 'checkpoint',
    chineseLabel: '可恢复进度点',
    category: 'harness',
    level: 2,
    position: [-3, -2.2, 2.3],
    kind: 'satellite',
    parentId: 'compaction',
    responsibility: '保存能够恢复任务的状态和关键证据引用。',
    related: ['state', 'compaction'],
  },

  {
    id: 'web',
    chineseLabel: '网页搜索',
    category: 'external',
    level: 2,
    position: [11.6, 2.5, -3.3],
    kind: 'tool',
    parentId: 'external',
    responsibility: '在授权范围内搜索网页，返回候选来源。',
    related: ['browser', 'rag'],
  },
  {
    id: 'files',
    chineseLabel: '文件与 PDF',
    category: 'external',
    level: 2,
    position: [9.8, 2.8, -7.5],
    kind: 'tool',
    parentId: 'external',
    responsibility: '读取指定文件及其页码内容，返回可定位的资料。',
    related: ['rag', 'memory'],
  },
  {
    id: 'code',
    chineseLabel: '代码环境',
    category: 'external',
    level: 2,
    position: [12.8, 0.3, -7],
    kind: 'tool',
    parentId: 'external',
    responsibility: '在受控环境中运行代码和测试，并返回真实执行结果。',
    related: ['verifier'],
  },
  {
    id: 'database',
    chineseLabel: '外部数据库',
    category: 'external',
    level: 2,
    position: [12.9, -2, -3.9],
    kind: 'tool',
    parentId: 'external',
    responsibility: '根据授权查询或更新结构化记录。',
    related: ['vector-db', 'memory'],
  },
  {
    id: 'browser',
    chineseLabel: '浏览器',
    category: 'external',
    level: 2,
    position: [9.6, 4.6, -4.7],
    kind: 'tool',
    parentId: 'external',
    responsibility: '打开页面并读取可见内容；能否执行操作由权限和运行系统限制。',
    related: ['web'],
  },
  {
    id: 'api',
    chineseLabel: '服务接口',
    category: 'external',
    level: 2,
    position: [9.2, -2.1, -7.2],
    kind: 'tool',
    parentId: 'external',
    responsibility: '按约定调用外部服务，返回结构化响应或错误。',
    related: ['mcp'],
  },
  {
    id: 'mcp-server',
    chineseLabel: 'MCP 能力服务',
    category: 'external',
    level: 2,
    position: [7.5, 2, -7.1],
    kind: 'satellite',
    parentId: 'external',
    responsibility: '按 MCP 协议暴露工具、资源或提示模板。',
    related: ['mcp-client', 'transport', 'mcp'],
  },
  {
    id: 'resource',
    chineseLabel: '可读取资源',
    category: 'external',
    level: 2,
    position: [6.7, 4, -8.6],
    kind: 'satellite',
    parentId: 'mcp-server',
    responsibility: '让客户端读取服务器暴露的资料，是否入 Context 由宿主决定。',
    related: ['tools', 'mcp-prompt'],
  },
  {
    id: 'mcp-prompt',
    chineseLabel: '提示模板',
    category: 'external',
    level: 2,
    position: [8.7, 4.6, -9],
    kind: 'satellite',
    parentId: 'mcp-server',
    responsibility: '提供可由客户端选用的交互模板。',
    related: ['prompt', 'resource'],
  },
  {
    id: 'transport',
    chineseLabel: '消息通道',
    category: 'external',
    level: 2,
    position: [5.5, 0.2, -6.8],
    kind: 'satellite',
    parentId: 'mcp-server',
    responsibility: '在客户端与服务器之间承载协议消息。',
    related: ['mcp-client', 'mcp-server'],
  },
  {
    id: 'observation',
    chineseLabel: '执行结果与反馈',
    category: 'external',
    level: 2,
    position: [7.2, -2.8, -5.1],
    kind: 'satellite',
    parentId: 'external',
    responsibility: '接收真正的工具结果，整理后返回 Context 供模型重新判断。',
    related: ['retrieved-context', 'loop'],
  },

  {
    id: 'approval',
    chineseLabel: '人工决定',
    category: 'verification',
    level: 2,
    position: [8.8, 1.2, 4.6],
    kind: 'gate',
    parentId: 'guardrail',
    responsibility: '对需要人工介入的关键动作明确批准或拒绝；等待不算批准。',
    related: ['guardrail'],
  },
  {
    id: 'eval',
    chineseLabel: '系统评估',
    category: 'verification',
    level: 2,
    position: [5.8, 1.9, 7.8],
    kind: 'check',
    parentId: 'verifier',
    responsibility: '在一组任务上按统一标准比较系统能力和质量。',
    related: ['verifier', 'trace'],
  },
]

const supplemental: Record<
  string,
  Pick<ExploreNode, 'label' | 'description' | 'technicalDefinition' | 'confused' | 'lessonId'>
> = {
  state: {
    label: 'State',
    description: '保存任务现在进行到了哪里。',
    technicalDefinition:
      '运行系统维护的当前执行状态，包括任务阶段、已有结果、决策与待办；可按系统需要持久化。',
    confused: 'State 是当前状态；Trace 是过程记录。二者都不自动等于 Memory。',
    lessonId: 'harness',
  },
  trace: {
    label: 'Trace',
    description: '留下一路做过什么的记录。',
    technicalDefinition: '对系统运行事件、调用、结果、检查与时序的记录，用于追踪、调试和评估。',
    confused: 'Trace 不一定全部进入 Context，也不自动写成长期 Memory。',
    lessonId: 'harness',
  },
  retry: {
    label: 'Retry',
    description: '出错后，按规则再试一次。',
    technicalDefinition: '对可恢复错误按重试次数、退避与幂等条件等策略再次执行操作的机制。',
    confused: '重试不是无条件重复，更不应绕过权限或反复执行有副作用的动作。',
    lessonId: 'harness',
  },
  web: {
    label: 'Web Search',
    description: '请搜索工具找出可能有用的网页。',
    technicalDefinition: '由运行系统执行的网页检索能力，返回候选页面、摘要或来源元数据。',
    confused: '搜索结果不保证可靠；模型生成搜索请求也不代表已经搜索。',
    lessonId: 'tools',
  },
  files: {
    label: 'Files / PDF',
    description: '打开指定文件，取出需要的资料。',
    technicalDefinition:
      '由文件工具在授权范围内读取指定文件或 PDF 的内容，并返回文本、页面或元数据。',
    confused: '读取一份指定 PDF 不等于从整个资料库做 RAG 检索。',
    lessonId: 'tools',
  },
  code: {
    label: 'Code Runtime',
    description: '真正运行代码，再看输出或报错。',
    technicalDefinition: '受运行系统管理的代码执行环境，可产生输出、退出状态和测试结果。',
    confused: '模型写出代码不等于代码运行成功；测试结果需来自实际执行。',
    lessonId: 'verification',
  },
  database: {
    label: 'Database',
    description: '按条件读取或更新外部记录。',
    technicalDefinition: '提供结构化数据存储与查询的外部系统，工具依据权限和查询条件访问。',
    confused: '数据库是存储技术，Memory 是系统能力；两者不能直接等同。',
    lessonId: 'tools',
  },
  browser: {
    label: 'Browser',
    description: '打开网页，看页面里实际写了什么。',
    technicalDefinition: '支持导航、读取或操作网页状态的外部能力，由运行系统执行授权动作。',
    confused: '打开网页与搜索网页不是同一步；网页内容也不天然可信。',
    lessonId: 'tools',
  },
  api: {
    label: 'API',
    description: '按双方约定向外部服务提出请求。',
    technicalDefinition: '软件系统暴露的调用接口，按约定接收参数并返回响应。',
    confused: '普通 API 不一定采用 MCP；MCP 是连接能力的协议层。',
    lessonId: 'mcp',
  },
}

const connect = (
  from: string,
  to: string,
  type: ExploreConnection['type'],
  label: string,
): ExploreConnection => ({ id: `${from}-${to}`, from, to, type, label })

// Principal paths come first so collapsed views retain their educational labels.
export const exploreConnections: ExploreConnection[] = [
  connect('user', 'prompt', 'data', '任务与要求'),
  connect('prompt', 'context', 'data', '要求进入本次上下文'),
  connect('context', 'model', 'data', '本次可见信息'),
  connect('model', 'call', 'control', '生成请求，尚未执行'),
  connect('call', 'harness', 'control', '交给运行系统'),
  connect('harness', 'tools', 'tool', '检查后调度执行'),
  connect('tools', 'external', 'tool', '授权访问外部资源'),
  connect('external', 'observation', 'data', '返回执行结果'),
  connect('observation', 'context', 'data', '结果整理后回到上下文'),
  connect('model', 'verifier', 'control', '提交候选结果检查'),
  connect('verifier', 'loop', 'loop', 'FAIL：带着缺口继续'),
  connect('loop', 'context', 'loop', '补充反馈，开始下一轮'),
  connect('verifier', 'final', 'control', 'PASS：允许交付'),
  connect('memory', 'context', 'retrieval', '取回相关记忆'),
  connect('rag', 'context', 'retrieval', '相关片段加入上下文'),
  connect('history', 'context', 'data', '保留有用历史'),
  connect('schema', 'context', 'data', '提供可用工具说明'),
  connect('user', 'router', 'control', '接收输入'),
  connect('router', 'context-engineering', 'control', '选择处理路径'),
  connect('context-engineering', 'context', 'control', '选择与组织本次信息'),
  connect('context', 'compaction', 'control', '历史接近预算时压缩'),
  connect('compaction', 'context', 'data', '保留关键状态的摘要'),
  connect('compaction', 'checkpoint', 'data', '保存可恢复进度'),
  connect('context-window', 'compaction', 'control', '上下文容量约束'),
  connect('retrieval', 'rerank', 'retrieval', '候选资料'),
  connect('rerank', 'retrieved-context', 'retrieval', '筛出相关片段'),
  connect('retrieved-context', 'context', 'retrieval', '本次选中的资料'),
  connect('vector-db', 'retrieval', 'retrieval', '向量检索可用的候选'),
  connect('rag', 'retrieval', 'control', '发起相关资料检索'),
  connect('embedding', 'vector-db', 'data', '供索引使用的向量表示'),
  connect('model', 'reasoning', 'data', '分析与判断的教学摘要'),
  connect('model', 'planning', 'data', '形成或调整计划'),
  connect('model', 'function-calling', 'control', '选择结构化输出机制'),
  connect('function-calling', 'call', 'control', '生成结构化工具请求'),
  connect('schema', 'call', 'data', '调用名称与参数约定'),
  connect('token', 'embedding', 'data', '编码输入片段'),
  connect('embedding', 'attention', 'data', '数字表示参与关系计算'),
  connect('attention', 'transformer', 'data', 'Attention 是架构组成机制'),
  connect('harness', 'guardrail', 'control', '检查权限和动作边界'),
  connect('guardrail', 'tools', 'control', '符合策略的动作放行'),
  connect('guardrail', 'approval', 'control', '需人工判断时暂停'),
  connect('approval', 'tools', 'control', '明确批准后才继续'),
  connect('harness', 'state', 'data', '持续更新执行状态'),
  connect('harness', 'trace', 'data', '持续记录运行事件'),
  connect('harness', 'retry', 'control', '应用重试策略'),
  connect('retry', 'tools', 'tool', '满足条件时重试'),
  connect('harness', 'loop', 'control', '调度循环与停止条件'),
  connect('harness', 'mcp', 'tool', '可选：采用 MCP 连接'),
  connect('mcp', 'mcp-client', 'tool', '宿主内的协议客户端'),
  connect('mcp-client', 'mcp-server', 'tool', '交换协议请求与结果'),
  connect('mcp-server', 'external', 'tool', '暴露外部能力'),
  connect('mcp-server', 'resource', 'data', '提供可读取资源'),
  connect('mcp-server', 'mcp-prompt', 'data', '提供可选提示模板'),
  connect('transport', 'mcp-server', 'tool', '承载协议消息'),
  connect('resource', 'context-engineering', 'data', '交给宿主选择是否入上下文'),
  connect('mcp-prompt', 'context-engineering', 'data', '选用后组织输入'),
  connect('tools', 'web', 'tool', '搜索候选网页'),
  connect('tools', 'files', 'tool', '读取指定文件'),
  connect('tools', 'code', 'tool', '在受控环境运行代码'),
  connect('tools', 'database', 'tool', '按授权查询或更新'),
  connect('tools', 'browser', 'tool', '打开并读取网页'),
  connect('tools', 'api', 'tool', '调用外部接口'),
  connect('web', 'observation', 'data', '候选网页与来源'),
  connect('files', 'observation', 'data', '文件内容与定位信息'),
  connect('browser', 'observation', 'data', '实际页面内容'),
  connect('code', 'observation', 'data', '代码输出与退出状态'),
  connect('database', 'observation', 'data', '查询结果或操作状态'),
  connect('api', 'observation', 'data', '响应或错误'),
  connect('state', 'checkpoint', 'data', '可恢复的任务状态'),
  connect('final', 'trace', 'data', '记录本轮交付与证据'),
  connect('state', 'memory', 'data', '按规则选择有用信息保存'),
  connect('trace', 'eval', 'data', '提供可评估的运行证据'),
  connect('workflow', 'harness', 'control', '执行预定义路径'),
  connect('agent', 'harness', 'control', '落实动态行动决策'),
  connect('multi-agent', 'agent-as-tool', 'control', '委派后接收子任务结果'),
  connect('multi-agent', 'handoff', 'control', '转移后续控制权'),
  connect('react', 'loop', 'control', '判断、行动、观察的经典思想'),
]

const sourceById = new Map(concepts.map((item) => [item.id, item]))

export const exploreNodes: ExploreNode[] = placements.map((placement) => {
  const source = sourceById.get(placement.id)
  const additional = supplemental[placement.id]
  if (!source && !additional) throw new Error(`Missing concept definition: ${placement.id}`)
  return {
    ...placement,
    label: additional?.label ?? source!.name,
    description: additional?.description ?? source!.plain,
    technicalDefinition: additional?.technicalDefinition ?? source!.definition,
    confused: additional?.confused ?? source!.confused,
    lessonId: additional?.lessonId ?? source!.lesson,
    upstream: exploreConnections
      .filter((edge) => edge.to === placement.id)
      .map((edge) => edge.from),
    downstream: exploreConnections
      .filter((edge) => edge.from === placement.id)
      .map((edge) => edge.to),
    related: [
      ...new Set([
        ...(placement.related ?? []),
        ...placements
          .filter((other) => other.related?.includes(placement.id))
          .map((other) => other.id),
      ]),
    ],
  }
})

export const taskSteps: ExploreTaskStep[] = [
  {
    id: 'request',
    title: '用户提出 GPU 研究任务',
    nodeId: 'user',
    edgeIds: ['user-prompt'],
    explanation:
      '目标是研究最新 AI GPU，并整理中文报告。要求每条关键结论有来源；这里的来源和执行结果都是教学模拟。',
    message: '任务：比较 AI GPU，列出来源与不确定项。',
  },
  {
    id: 'context',
    title: '组织模型这次能看到的信息',
    nodeId: 'context',
    edgeIds: ['prompt-context', 'memory-context', 'rag-context'],
    explanation:
      '任务要求、相关历史偏好和内部资料库检索出的少量 PDF 片段进入 Context。Memory 不会整体搬进来，RAG 也不会改变模型参数。',
    message: 'Context = 要求 + 中文偏好 + 相关 PDF 片段 + 工具说明。',
  },
  {
    id: 'model',
    title: '模型判断还缺公开资料',
    nodeId: 'model',
    edgeIds: ['context-model'],
    explanation:
      '仅靠内部资料不足以回答“最新”。模型根据当前输入选择请求网页检索；外部资料还没有被访问。',
    message: '教学判断摘要：需要新资料和可追溯来源。',
  },
  {
    id: 'call',
    title: '生成搜索请求单',
    nodeId: 'call',
    edgeIds: ['model-call'],
    explanation: '模型写出具体工具名称和参数。生成 Tool Call 只是提出请求，尚未真正搜索。',
    message: '模拟请求：web.search({ query: "最新 AI GPU 官方参数" })',
  },
  {
    id: 'execute',
    title: '运行系统检查并调度',
    nodeId: 'harness',
    edgeIds: ['call-harness', 'harness-guardrail', 'harness-tools'],
    explanation:
      'Harness 检查工具是否可用、动作是否允许，并把合规的只读搜索交给工具。过程同步更新 State 和 Trace。',
    message: '只读搜索符合策略 → 调度工具执行。',
  },
  {
    id: 'search',
    title: '工具访问外部网页',
    nodeId: 'web',
    edgeIds: ['tools-web'],
    explanation: '现在才发生外部检索。教学情境中，第一轮只返回论坛转载，缺少直接的官方依据。',
    message: '模拟结果：论坛转载；未获得官方来源。',
  },
  {
    id: 'observe',
    title: '实际结果回到工作台',
    nodeId: 'observation',
    edgeIds: ['web-observation', 'observation-context'],
    explanation:
      '工具结果成为 Observation，经组织加入 Context。模型看到的是刚收到的结果，不应把猜测当成已经执行的事实。',
    message: '结果已加入 Context：来源可信度待核验。',
  },
  {
    id: 'draft',
    title: '根据现有证据形成候选结果',
    nodeId: 'model',
    edgeIds: ['context-model', 'model-verifier'],
    explanation: '模型整理出候选结论，并把来源缺口交给检查环节。文字看起来完整并不代表任务完成。',
    message: '候选报告就绪；仍需核查来源与覆盖范围。',
  },
  {
    id: 'fail',
    title: '检查失败：没有官方证据',
    nodeId: 'verifier',
    edgeIds: ['model-verifier', 'verifier-loop'],
    explanation:
      '要求是关键结论可追溯到可靠来源。第一版只有论坛转载，因此检查为 FAIL，不能从这里直接交付。',
    message: 'FAIL · 缺少官方来源与可定位的证据。',
    outcome: 'fail',
  },
  {
    id: 'loop',
    title: '带着失败原因进入下一轮',
    nodeId: 'loop',
    edgeIds: ['verifier-loop', 'loop-context'],
    explanation: 'Agent Loop 把“缺官方证据”作为新信息送回 Context，让下一轮有明确的修复方向。',
    message: '下一轮目标：打开官方资料，核对关键参数。',
  },
  {
    id: 'compact',
    title: '保留关键线索，缩短历史记录',
    nodeId: 'compaction',
    edgeIds: ['context-compaction', 'compaction-context', 'compaction-checkpoint'],
    explanation:
      '模拟较长研究任务接近 Context 预算：压缩重复日志，保留目标、引用、失败原因与待办。跨任务 Memory 仍然保存。',
    message: '摘要保留：任务要求、内部资料引用、来源缺口与下一步。',
  },
  {
    id: 'second-call',
    title: '请求打开官方资料',
    nodeId: 'call',
    edgeIds: ['context-model', 'model-call', 'call-harness'],
    explanation:
      '模型看过更新的 Context 后，生成打开官方资料的请求。Harness 仍然负责检查和执行，模型不直接上网。',
    message: '模拟请求：browser.open({ source: "官方产品资料" })',
  },
  {
    id: 'official',
    title: '运行系统再次执行工具',
    nodeId: 'browser',
    edgeIds: ['harness-tools', 'tools-browser'],
    explanation:
      'Harness 调度浏览器读取官方页面，同时保留页面位置和发布日期用于核验。本步骤展示教学数据，不是真实浏览结果。',
    message: '模拟结果：官方参数页与发布说明，可定位来源。',
  },
  {
    id: 'new-observation',
    title: '新证据重新进入 Context',
    nodeId: 'observation',
    edgeIds: ['browser-observation', 'observation-context'],
    explanation:
      '官方资料与已选入的内部 PDF 片段共同成为这一次可见的依据。系统只整理需要的部分，而不是把外部世界全部交给模型。',
    message: '已补齐：官方来源 + 内部资料定位 + 未确认项。',
  },
  {
    id: 'revise',
    title: '模型依据证据修订报告',
    nodeId: 'model',
    edgeIds: ['context-model', 'model-verifier'],
    explanation:
      '模型修订比较表，给关键结论附上来源，并明确不同指标口径与不确定项。完成后再次提交检查。',
    message: '候选报告：结论、来源、适用条件与局限。',
  },
  {
    id: 'pass',
    title: '逐项核验通过',
    nodeId: 'verifier',
    edgeIds: ['model-verifier', 'verifier-final'],
    explanation:
      '教学检查表核对来源定位、内部资料引用、关键结论与任务要求，全部满足后才给出 PASS。它不是“模型说自己对了”。',
    message: 'PASS · 来源可追溯，引用齐全，要求已逐项核对。',
    outcome: 'pass',
  },
  {
    id: 'final',
    title: '交付经过检查的报告',
    nodeId: 'final',
    edgeIds: ['verifier-final', 'final-trace'],
    explanation:
      '系统把报告与引用交给用户，并在 Trace 中记录交付。只有适合以后使用的信息，才会按规则选择写入 Memory。',
    message: '已交付：GPU 比较报告、来源清单与不确定项。',
  },
]

export const tourStops: ExploreTourStop[] = [
  {
    nodeId: 'context',
    title: '先看模型的工作台',
    question: '模型这一次到底能看到哪些东西？',
    explanation:
      'Context 位于模型之前。要求、相关记忆、检索资料和工具结果只有进入这里，才成为本次推理的输入。',
  },
  {
    nodeId: 'model',
    title: '找到生成与决策核心',
    question: '模型生成一个工具请求，外部操作就完成了吗？',
    explanation:
      'Model 处理 Context 并生成回答或请求。它需要把工具请求交给 Harness，才能连接实际行动。',
  },
  {
    nodeId: 'tools',
    title: '看看谁在实际行动',
    question: '搜索、读取 PDF 和运行代码是谁完成的？',
    explanation:
      'Tools 是可调用能力，按运行系统的调度执行。执行结果沿回流连接返回 Context，供模型继续判断。',
  },
  {
    nodeId: 'harness',
    title: '认识让系统运转的底座',
    question: '为什么 Model 与 Tool 之间还需要一层？',
    explanation:
      'Harness 负责组织信息、检查权限、调度工具、记录状态与推进循环。模型的请求必须由这个运行系统落实。',
  },
  {
    nodeId: 'loop',
    title: '看到任务怎样继续',
    question: '第一轮结果不够好，接下来怎么办？',
    explanation:
      'Agent Loop 把反馈带入下一轮 Context。失败意味着继续补充、修复或按条件停止，不能直接冒充成功。',
  },
  {
    nodeId: 'rag',
    title: '让资料有选择地进入工作台',
    question: '资料库很大，怎么只给模型需要的部分？',
    explanation:
      'RAG 检索相关内容，选择少量片段加入 Context。它靠近 Context，表达的是提供本次依据，而不是训练模型。',
  },
  {
    nodeId: 'memory',
    title: '把跨任务的信息存起来',
    question: '上次的偏好怎么在这次派上用场？',
    explanation:
      'Memory 保存可跨任务使用的信息。只有取出的相关内容才会进入当前 Context，所以记忆仓与工作台是两个概念。',
  },
  {
    nodeId: 'verifier',
    title: '用证据判断是否完成',
    question: '为什么 FAIL 的连接返回 Loop？',
    explanation:
      '核验需要可检查条件。未满足要求就把缺口交回 Loop；满足要求的 PASS 路径才通向 Final。',
  },
  {
    nodeId: 'guardrail',
    title: '在行动边界前做检查',
    question: '任何请求都能马上执行吗？',
    explanation:
      'Guardrail 检查动作和权限。低风险动作可按策略放行，高风险动作可能拒绝或等待人工明确决定。',
  },
  {
    nodeId: 'mcp',
    title: '理解可选的标准连接方式',
    question: 'MCP 是模型，还是连接外部能力的协议？',
    explanation:
      'MCP 让宿主客户端与能力服务器按标准协议交流。它不负责代替模型思考，也不是全部工具调用必须经过的通道。',
  },
  {
    nodeId: 'workflow',
    title: '区分预设路径与动态决策',
    question: '流程能提前写好，和 Agent 动态决定有什么不同？',
    explanation:
      'Workflow 的执行路径由程序定义，也能有条件分支。Agent 则由模型根据当前状态动态选择下一步；系统可结合两者。',
  },
  {
    nodeId: 'multi-agent',
    title: '看看协作边界',
    question: '委派子任务与转交负责人是一回事吗？',
    explanation:
      'Agent-as-Tool 返回结果给管理者；Handoff 转移后续控制权。多个 Agent 需要清楚的职责与信息边界。',
  },
  {
    nodeId: 'compaction',
    title: '让长任务带着线索继续',
    question: 'Context 快满时，是不是应该删除长期记忆？',
    explanation:
      'Compaction 压缩历史 Context，并保留目标、证据引用、状态和待办。它不会删除 Memory，也不会无限扩大 Context Window。',
  },
]
